version: 0.0.1
achievements:
  - achievement:
      name: Visionary Architect
      icon: https://raw.githubusercontent.com/answerdev/answer/main/.vaunt/enhancement.png
      description: Awarded for bringing up enhancement, dream big!
      triggers:
        - trigger:
            actor: assignees
            action: issue
            condition: labels in ['enhancement'] & labels in ['LGTM']
  - achievement:
      name: Bug Hunter
      icon: https://raw.githubusercontent.com/answerdev/answer/main/.vaunt/bug.png
      description: Awarded for identifying real bugs, well spotted!
      triggers:
        - trigger:
            actor: assignees
            action: issue
            condition: labels in ['bug'] & labels in ['LGTM']
